/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.codeFellowship;

import org.junit.jupiter.api.Test;

class CodefellowshipApplicationTest {
    @Test void appHasAGreeting() {

    }
}
